### ISSUE TITLE
Command line arguments

### ISSUE THREAD

**Issue by Chucky2401** [BlobBackup/BlobBackup#43]
Hi,
I discover your software through GHacks website. It's very usefull!

Unfortunately, I discover that it not starts with Windows by default, and I didn't find the option. I can add myself a registry key or put a shortcut in the startup folder or create a schedule task.
But, does exist an argument to start the app minimize? I think it would be very interesting to have some command line arguments like: 
- Start minimized
- Run all backup jobs
- Run one job by the name and/or id
- etc.

It's just an idead.

Thank you.
Regards

**Comment by bimbashrestha** [comment]
@Chucky2401 thanks for posting and welcome to the project! 

I really like the idea of allowing the user to specify whether to start the app minimized or maximized. I think this should be pretty easy to implement too. I'll make sure it's added soon.

The other ones are interesting too. We'll have to see how much demand there is for them as so far most users have preferred the GUI. But definitely worth noting. I'm going to keep them in the backlog for now.

**Comment by bimbashrestha** [comment]
https://github.com/BlobBackup/BlobBackup/issues/38

I also want to make a proper CLI at some point with a user interface similar to borg or restic.

**Comment by bimbashrestha** [comment]
Hi @Chucky2401. I just added the `--open-minimized` flag which allows you to open BlobBackup without opening the main window. Do you mind giving it a shot when you have a chance?

**Comment by Chucky2401** [comment]
Hi bimbashrestha.
Thank you for your patience, I had some urgent issues.

Do you have a setup package for Windows? I tried to install it with the `build-windows.ps1` and `pip` but it doesn't want to run...

Thank you.

**Comment by bimbashrestha** [comment]
Hi @Chucky2401, sorry for the late reply on my end as well. 

Do you mind telling me how you tried to run with `pip` and what error you encountered?. My understanding and memory tells me that it should work.

**Comment by Chucky2401** [comment]
Hi @bimbashrestha, no problem.

Yes, of course.
At the beginning, I had Python 3.8 installed from the Microsoft store. I had a lot of errors, so I removed it, and I installed Python 3.7 as you mention in the Readme.

The installation finished with this message:
`Successfully installed blobbackup-1.0.0b3`
But, when I ran blobbackup, I got this:
```
PS D:\Utilisateurs\TheBlackWizard\Logiciels\Git\blobbackup> blobbackup
Traceback (most recent call last):
  File "D:\Python\Python37\Scripts\blobbackup-script.py", line 11, in <module>
    load_entry_point('blobbackup==1.0.0b3', 'console_scripts', 'blobbackup')()
  File "d:\python\python37\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "d:\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "d:\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2462, in load
    return self.resolve()
  File "d:\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "d:\python\python37\lib\site-packages\blobbackup\application.py", line 11, in <module>
    from blobbackup.main_window import MainWindow
  File "d:\python\python37\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "d:\python\python37\lib\site-packages\blobbackup\main_window.py", line 10, in <module>
    from blobbackup.config_local_dialog import ConfigLocalDialog
  File "d:\python\python37\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "d:\python\python37\lib\site-packages\blobbackup\config_local_dialog.py", line 3, in <module>
    from blobbackup.validator import Validator
  File "d:\python\python37\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "d:\python\python37\lib\site-packages\blobbackup\validator.py", line 2, in <module>
    from blobbackup.models import Backups, Utils
  File "d:\python\python37\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "d:\python\python37\lib\site-packages\blobbackup\models.py", line 10, in <module>
    import win32timezone
  File "d:\python\python37\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'win32timezone'
```

So, I tried to ran `build-windows.ps1`, it finished and I get the folder `.\blobbackup\build\BlobBackup` with an executable. When I ran this executable, I get this fatal error:
`Failed to execute script pyi_rth_kgres`, even if I copy this file in the previous installation folder with the msi file.

Maybe I need to uninstall the previous version? I don't know, but I'm sure you will find a solution 😉

**Comment by bimbashrestha** [comment]
Hi @Chucky2401 thanks for the information. Looks like you found a bug. I forgot to include the `pywin32` dependency in `setup.py`. Should be an easy fix. Will put up a PR shortly for it

**Comment by bimbashrestha** [comment]
Okay @Chucky2401, the `pip` installation should now be fixed with this commit: https://github.com/BlobBackup/BlobBackup/commit/af46e6500d876bf21c7e26e8b17e5cc97d711a70. Thank you for testing and reporting back!

**Comment by laedit** [comment]
I have tried `.\BlobBackup.exe --open-minimized` but the main window is still shown.

**Comment by bimbashrestha** [comment]
@laedit just to confirm, you try using the `dev` branch right (after compiling on windows) instead of using the latest release (which doesn't have it yet). Thanks!

**Comment by laedit** [comment]
Oh sorry, I thought it was on the latest release.
I am not familiar with python application dev, and I have an issue with installing the requirements:
``` bash
WARNING: Discarding https://files.pythonhosted.org/packages/69/2a/298b2689bee8e88c502c7e85ba1c9f07c7e182ea91c705c449f693056c9f/pycryptodome-3.9.7.tar.gz#sha256=f1add21b6d179179b3c177c33d18a2186a09cc0d3af41ff5ed3f377360b869f2 (from https://pypi.org/simple/pycryptodome/) (requires-python:>=2.6, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pycryptodome==3.9.7 (from versions: 3.0rc1, 3.0, 3.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.4, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 3.4.9, 3.4.11, 3.5.0, 3.5.1, 3.6.0, 3.6.1, 3.6.3, 3.6.4, 3.6.5, 3.6.6, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.8.0, 3.8.1, 3.8.2, 3.9.0, 3.9.1, 3.9.2, 3.9.3, 3.9.4, 3.9.6, 3.9.7, 3.9.8, 3.9.9, 3.10.1, 3.10.3, 3.10.4, 3.11.0)
ERROR: No matching distribution found for pycryptodome==3.9.7
```
I am using python 3.9.7 so I don't understand why the version of pycryptodome is being discarded.

**Comment by laedit** [comment]
I got this error when trying to test the BlobBackup.exe in the dist folder:
`Failed to execute script 'application' due to unhandled exception: 'Europe/Paris'`
And the details:
```
Traceback (most recent call last):
  File "zoneinfo\_common.py", line 12, in load_tzdata
  File "importlib\resources.py", line 88, in open_binary
  File "importlib\resources.py", line 49, in _get_package
  File "importlib\resources.py", line 40, in _resolve
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tzdata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pytz_deprecation_shim\_impl.py", line 39, in timezone
  File "pytz_deprecation_shim\_compat_py3.py", line 16, in get_timezone
  File "zoneinfo\_common.py", line 24, in load_tzdata
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key Europe/Paris'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "blobbackup\application.py", line 106, in <module>
  File "blobbackup\application.py", line 101, in main
  File "blobbackup\application.py", line 27, in __init__
  File "blobbackup\scheduler.py", line 9, in __init__
  File "apscheduler\schedulers\base.py", line 87, in __init__
  File "apscheduler\schedulers\base.py", line 131, in configure
  File "apscheduler\schedulers\background.py", line 29, in _configure
  File "apscheduler\schedulers\base.py", line 702, in _configure
  File "tzlocal\win32.py", line 119, in get_localzone
  File "pytz_deprecation_shim\_impl.py", line 41, in timezone
pytz_deprecation_shim._exceptions._make_pytz_derived_errors.<locals>.UnknownTimeZoneError: 'Europe/Paris'
```

**Comment by laedit** [comment]
But it works well when launching directly `application.py`! 😃  
The parameter `--open-minimized` is validated.
